# Example GitHub Actions workflow for frontend tests
# This is a REFERENCE ONLY - adapt to your existing workflow

name: Frontend Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      # Optional: Set custom API URL (not required - tests use mocks)
      - name: Set API URL (optional)
        run: echo "REACT_APP_API_URL=http://localhost:8080" >> $GITHUB_ENV
      
      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watchAll=false --passWithNoTests --coverage
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          directory: frontend/coverage
          flags: frontend
          fail_ci_if_error: false

# NOTE: Backend is NOT required to run these tests
# All API calls are mocked using Jest
# Tests will pass without any backend services running
